### ISSUE TITLE
Trigger a compilation warning when using a deprecated field

### ISSUE THREAD

**Issue by romanschejbal** [reasonml-community/graphql_ppx#73]
It's important for us to know when we are using field that's been deprecated so we can keep up to date with the backend.

**Comment by baransu** [comment]
Great idea! We should have all the required information for that!

**Comment by romanschejbal** [comment]
Yeah I'm just looking into it and it seems like I can do this inside [result_decoder](https://github.com/reasonml-community/graphql_ppx/blob/master/src/base/result_decoder.re#L313) - would that be correct? What would I use for logging the warning message?

**Comment by baransu** [comment]
Probably the best option would be to add it here: https://github.com/reasonml-community/graphql_ppx/blob/master/src/base/validations.re#L3

It's a list of all validators that are checking out schema. Here is an example validator: https://github.com/reasonml-community/graphql_ppx/blob/master/src/base/rule_no_unused_variables.re

It's traversing your whole schema query and based on that you can add errors to context. What is lacking right now is context's support to emit warnings instead of errors. It should be implemented here probably: https://github.com/reasonml-community/graphql_ppx/blob/master/src/base/traversal_utils.re#L8
and handled here somehow: https://github.com/reasonml-community/graphql_ppx/blob/b6d473ff4b28bd79452c2ce967e9da907b43ffad/src/bucklescript/graphql_ppx.re#L99

**Comment by romanschejbal** [comment]
Ace, I will give it a go :-) thanks for guidance
