### ISSUE TITLE
Option types for nullable scalar inputs in makeVariables?

### ISSUE THREAD

**Issue by nirvdrum** [reasonml-community/graphql_ppx#99]
My GraphQL schema has a nullable `String` field that gets mapped as `option(string)` when mapping the response to a record. However, I don't see a parallel for mutations to set that value. In this case, I've specified the argument as `$note: String`, which I would expect to be treated as `option(string)` in `makeVariables`, but it's being treated as `string`. Am I just overlooking something? If not, how do I set a field to `null`?

**Comment by jfrolich** [comment]
See https://github.com/reasonml-community/graphql_ppx/issues/26.

For now, it's not possible to pass null to a mutation, because reason doesn't have the concept of undefined vs null. We will add this support in 1.0 probably through a query flag where you can pass Some(None) to be explicitly able to pass null into a mutation.

**Comment by nirvdrum** [comment]
Thanks. I had come across that issue and thought it was about something else. But, reading through, I can see they address the same core problem. I'll close this one out in favor of that.
